# Generated by Django 6.0.6 on 2026-06-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='contact_details',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
